version: '3'
services:
    server:
        image: nginx:alpine
        container_name: server
        restart: unless-stopped
        ports:
            - 81:80
            - 444:443
        networks:
            - app-network
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d/
#        command: chmod -R 777 /var/www/storage &&  chown -R nginx:nginx /var/www/storage

    app:
        build: .
        restart: unless-stopped
        container_name: laravel-php
        networks:
            - app-network
        volumes:
            - ./:/var/www
        command: sh -c "chmod -R 777 /var/www/storage && php-fpm"

    redis:
        image: redis:6
        container_name: laravel-redis
        volumes:
            - 'data.redis:/data'
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
    db:
        image: mariadb:10.2
        container_name: database
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        networks:
            - app-network
        restart: on-failure
        volumes:
            - db:/var/lib/mysql
volumes:
    db:
        driver: local
    data.redis:
        driver: local
networks:
    app-network:
        driver: bridge
