name: Build and Deploy Laravel app
on:
    push:
        branches:
            -   main

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@main
            -   name: Setup Enviroment
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
            -   name: Deploy to Server
                uses: easingthemes/ssh-deploy@main
                with:
                  SSH_PRIVATE_KEY: ${{ secrets.SECRET_PEM }}
                  ARGS: "-rlgoDzvc -i --delete "
                  SOURCE: "./"
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: "~/htdocs/backend_elsalvador"
                  EXCLUDE: "/dist/, /node_modules/, /vendor/"
                  SCRIPT_BEFORE: |
                    whoami
                    ls -al
                    cd ~/htdocs/backend_elsalvador
                    git pull origin main
                    sudo chown -R ${{ secrets.REMOTE_USER }}:${{ secrets.REMOTE_USER }} storage
                    sudo rm -rf storage
                    cp .env ../.env

            -   name: Build server
                uses: appleboy/ssh-action@master
                with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SECRET_PEM }}
                  port: 22
                  script: |
                    cd ~/htdocs/backend_elsalvador
                    cp ../.env .env
                    composer install --no-dev
                    php artisan migrate:fresh --seed
                    sudo chmod 775 storage
                    sudo chown -R daemon:www-data storage

