name: Build and Deploy Laravel app
on:
    push:
        branches:
            -   main

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@main
            -   name: Setup Enviroment
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
            -   name: Install Packages
                run: composer install --no-dev

            - name: 📂 Sync Production Config
              uses: easingthemes/ssh-deploy@v4.0.5
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SECRET_PEM }}
                REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                REMOTE_USER: ${{ secrets.REMOTE_USER }}
                SOURCE: config.production.json
                TARGET: /var/path.../
                ARGS: -rlgoDzvc -i -og --chown=user:user
            -   name: Deploy to Server
                run: |
                  ssh bitnami@3.93.57.139 "cd ~/htdocs/backend_elsalvador && git pull origin main"


                env:
                    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
