name: Build and Deploy Laravel app
on:
    push:
        branches:
            -   main

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@main
            -   name: Setup Enviroment
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
            -   name: Install Packages
                run: composer install --no-dev
            -   name: Deploy to Server
                uses: easingthemes/ssh-deploy@main
                with:
                  SSH_PRIVATE_KEY: ${{ secrets.SECRET_PEM }}
                  ARGS: "-rlgoDzvc -i --delete"
                  SOURCE: ""
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: "~/htdocs/backend_elsalvador"
                  EXCLUDE: "/dist/, /node_modules/, /vendor/"
            -   name: Run database
                run: |
                  cd ~/htdocs/backend_elsalvador && git pull origin main
                  php artisan migrate:fresh --seed


                env:
                    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
